version: '3'
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: scienest
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scienest
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    image: scienest
    ports:
      - 3000:3000
volumes:
  postgres-data:
    driver: local
